echo Generating cursor files...
xcursorgen alias.cursor alias
xcursorgen all-scroll.cursor all-scroll
xcursorgen bottom_left_corner.cursor bottom_left_corner
xcursorgen bottom_right_corner.cursor bottom_right_corner
xcursorgen bottom_side.cursor bottom_side
xcursorgen cell.cursor cell
xcursorgen center_ptr.cursor center_ptr
xcursorgen col-resize.cursor col-resize
xcursorgen color-picker.cursor color-picker
xcursorgen context-menu.cursor context-menu
xcursorgen copy.cursor copy
xcursorgen crosshair.cursor crosshair
xcursorgen down-arrow.cursor down-arrow
xcursorgen draft.cursor draft
xcursorgen dnd-move.cursor dnd-move
xcursorgen fleur.cursor fleur
xcursorgen left_side.cursor left_side
xcursorgen left-arrow.cursor left-arrow
xcursorgen no-drop.cursor no-drop
xcursorgen openhand.cursor openhand
xcursorgen pencil.cursor pencil
xcursorgen pirate.cursor pirate
xcursorgen progress.cursor progress
xcursorgen right_side.cursor right_side
xcursorgen right-arrow.cursor right-arrow
xcursorgen row-resize.cursor row-resize
xcursorgen size_ver.cursor size_ver
xcursorgen size_fdiag.cursor size_fdiag
xcursorgen size_bdiag.cursor size_bdiag
xcursorgen size_hor.cursor size_hor
xcursorgen size_ver.cursor size_ver
xcursorgen top_left_corner.cursor top_left_corner
xcursorgen top_right_corner.cursor top_right_corner
xcursorgen top_side.cursor top_side
xcursorgen up-arrow.cursor up-arrow
xcursorgen wait.cursor wait
xcursorgen dnd-no-drop.cursor dnd-no-drop
xcursorgen zoom-out.cursor zoom-out
xcursorgen zoom-in.cursor zoom-in
echo Finished generating cursor files