post_upgrade() {
    echo "=========================================================="
    echo " >>> IMPORTANT UPDATE NOTICE FOR v1.1 <<<"
    echo "=========================================================="
    echo "Please follow the migration steps here"
    echo "https://wiki.cachyos.org/configuration/desktop_environments/hyprland/#migrating-from-v4-dots-to-v5"
    echo "=========================================================="
}
