#!/usr/bin/env bash

update_kernel_list() {
    local kernel initramfs vmlinuz

    for pkgbase in /usr/lib/modules/*/pkgbase; do
        kernel="$(cat "$pkgbase")"
        initramfs="/boot/initramfs-${kernel}.img"
        vmlinuz="/boot/vmlinuz-${kernel}"

        limine-entry-tool --remove "${kernel}" --quiet
        [[ ! -e "$initramfs" ]] && continue
        [[ ! -e "$vmlinuz" ]] && continue
        limine-entry-tool --add "${kernel}" "$initramfs" "$vmlinuz" --quiet
    done
}

clean_kernel_list() {
    local kernel
    while IFS= read -r target; do
        kernel="$(cat /"$(dirname "$target")"/pkgbase)"
        limine-entry-tool --remove "${kernel}" --quiet
    done < <(tee /dev/null)
}

case "$1" in
    update)
        update_kernel_list
        ;;
    remove)
        clean_kernel_list
        ;;
    *)
        echo "Invalid argument" >&2
        exit 1
        ;;
esac
