#!/bin/bash

post_install() {
	/usr/bin/systemctl enable --now snapper-cleanup.timer
	#/usr/bin/systemctl enable snapper-timeline.timer

	echo "Creating snapper config for root subvolume"
	/usr/bin/snapper -c root create-config --template cachyos-root /

}

pre_remove() {
	echo "Deleting snapper configs"
	/usr/bin/snapper -c root delete-config
	echo "Disabling related snapper services"
	/usr/bin/systemctl disable --now snapper-cleanup.timer
	#/usr/bin/systemctl disable snapper-timeline.timer
}
