post_install() {
  mkdir $HOME/.config/menus/
  curl -L https://raw.githubusercontent.com/KDE/plasma-workspace/master/menu/desktop/plasma-applications.menu -o $HOME/.config/menus/applications.menu
  kbuildsycoca6
}

post_upgrade() {
  mkdir $HOME/.config/menus/
  curl -L https://raw.githubusercontent.com/KDE/plasma-workspace/master/menu/desktop/plasma-applications.menu -o $HOME/.config/menus/applications.menu
  kbuildsycoca6
}
