#!/bin/bash -e

while read -r line; do
	if [[ "${line}" == */pkgbase ]]; then
	    pkgbase="$(<"/${line}")"
	    kver="$(echo ${line} | cut -d/ -f4)"

# List of files to remove
files_to_remove=(
	"/usr/lib/modules/${kver}"
	"/boot/vmlinuz-${pkgbase}"
	"/boot/initramfs-${pkgbase}.img"
	"/boot/initramfs-${pkgbase}-fallback.img"
	"/boot/EFI/Linux/${pkgbase}.efi"
)

# Remove files
	for file in "${files_to_remove[@]}"; do
		rm -rf "${file}" 2> /dev/null
	done
	fi
done
