name: Bug Report
description: Report a broken or misbehaving package
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form as completely as possible. Incomplete reports are harder to act on.

  - type: input
    id: package
    attributes:
      label: Package name
      description: The name of the affected package (as it appears in this repository).
      placeholder: e.g. cachyos-hello
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package version
      description: The version of the package you are experiencing the issue with.
      placeholder: e.g. 1.2.3-1
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue type
      options:
        - Build failure
        - Runtime / functionality issue
        - Packaging error (wrong deps, missing files, etc.)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Install the package with ...
        2. Run ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error output
      description: Paste any relevant build logs, terminal output, or error messages here.
      render: shell

  - type: textarea
    id: bugreport
    attributes:
      label: CachyOS bug report
      description: |
        Run `sudo cachyos-bugreport.sh` and paste the URL to the uploaded log here.
        The script collects system information and uploads it automatically — only the link is needed.
        If you cannot run this script, please provide relevant system information (e.g. OS, kernel, hardware) instead.
      placeholder: https://paste.cachyos.org/...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information that may be relevant (workarounds tried, related issues, etc.).
