#!/bin/bash

set -e

kdialog \
--icon cachy-browser \
--title "Cachy Browser" \
--sorry "This browser is considered deprecated. Please migrate your profile to Firefox\nhttps://wiki.cachyos.org/support/faq/#migrating-your-profile-from-cachy-browser-to-firefox"
