[steam-jupiter-stable]
source = "regex"
url = "https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/"
regex = "steam-jupiter-stable-([\\d.]+)-\\d+-x86_64\\.pkg\\.tar\\.zst"
