post_install() {
        pacman-key --init
	pacman-key --add /usr/share/pacman/keyrings/cachyos.gpg
        pacman-key --lsign-key C3C4820857F654FE
	pacman-key --lsign-key BDED7D20D35BEF229712A1FE49B94AEF35812D6C
	pacman-key --lsign-key 4FF8FF1748568017C146718109D27738912724BE
	pacman-key --lsign-key 61324AC19819B2CFB5C69EB79215F8D0E3D6C128
	pacman-key --populate
}

post_upgrade() {
        post_install
}
