#!/usr/bin/env bash
# Copyright (C) 2025 CachyOS
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

function error() {
    echo "Error: $*" >&2
}
function die() {
    error "$@"
    exit 1
}

if ((EUID > 0)); then
    die "Run this script as root"
fi

if (($# < 1)); then
    die "Usage: $0 [package]..."
fi

function extract_package_modules() {
    local pkgname="$1"

    if ! pacman -Ssq "^$pkgname\$" &>/dev/null; then
        error "Package $pkgname is not found in any repository."
        error "Make sure your pacman configuration is correct."
        return 1
    fi

    local tmp="$(mktemp --suffix=extractor -d)"
    trap 'rm -rf -- "$tmp"' RETURN

    echo "Downloading $pkgname package..."

    # Workaround for DNS issues within the mkarchiso environment
    local -i is_resolv_conf_not_exist=0
    if [ ! -f /etc/resolv.conf ]; then
        is_resolv_conf_not_exist=1
        echo "nameserver 1.1.1.1" > /etc/resolv.conf
    fi

    local url="$(pacman -Swd --print "$pkgname")"
    curl -SOL --output-dir "$tmp" "$url" || {
        error "Failed to download $pkgname package"
        return 1
    }
    ((is_resolv_conf_not_exist)) && rm -f /etc/resolv.conf

    cd "$tmp"
    echo "Unpacking $pkgname package..."
    tar -xf "$pkgname"-*.pkg.tar.zst || {
        error "Failed to extract package tarball"
        return 1
    }

    if [ ! -e "$tmp/usr/lib/modules" ]; then
        error "Package $pkgname doesn't contain any kernel modules"
        return 1
    fi

    mkdir -p "/usr/share/modules/$pkgname"
    cp -v "$tmp/usr/lib/modules"/*/*.ko.zst "/usr/share/modules/$pkgname/"

    echo "Extracting modules for $pkgname is complete"
    return 0
}

for package; do
    extract_package_modules "$package"
done
