name: Check Package Versions

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 6 hours
  workflow_dispatch:     # Also allows manual trigger

jobs:
  check-versions:
    runs-on: ubuntu-latest

    env:
      GITHUB_REPO: 'CachyOS/CachyOS-PKGBUILDS'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt install -y jq nvchecker pacman-package-manager

      - name: Run version checker
        run: .github/scripts/checker.sh --ci
