jobs:
  validate-pkgbuilds:
    runs-on: ubuntu-latest
    container: cachyos/cachyos:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pacman -Syu --noconfirm namcap bun-bin

      - name: Validate PKGBUILDs
        run: bun .github/scripts/validate-pkgbuilds.js
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}

name: Validate PKGBUILDs

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to validate"
        required: true
        default: "master"
      sha:
        description: "SHA to validate"
        required: true
        default: "HEAD"
