name: Validate PKGBUILDs

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to validate"
        required: true
        default: "main"
      sha:
        description: "SHA to validate"
        required: true
        default: "HEAD"

jobs:
  validate-pkgbuilds:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pacman -Syu --noconfirm namcap curl unzip

      - name: Set up Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Validate PKGBUILDs
        run: ~/.bun/bin/bun .github/scripts/validate-pkgbuilds.js
