jobs:
  validate-pkgbuilds:
    runs-on: ubuntu-latest
    container: cachyos/cachyos:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # https://github.com/actions/checkout/issues/363
      - name: Fix Git safe directory issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install dependencies
        run: pacman -Syu --noconfirm namcap bun-bin
      - name: Validate PKGBUILDs
        run: bun .github/scripts/validate-pkgbuilds.js
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          BASE_REF: origin/${{ github.base_ref }}
          HEAD_REF: origin/${{ github.head_ref }}

name: Validate PKGBUILDs

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**/PKGBUILD"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to validate"
        required: true
        default: "master"
      sha:
        description: "SHA to validate"
        required: true
        default: "HEAD"
