#!/bin/bash

# Run cachyos hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    sed -i $file \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=cachyos|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"Cachy OS\"|'
}

Os_release() {
    local file=/usr/lib/os-release
    local cachyosfile=/usr/lib/cachyos-release

    sed -i $file \
        -e 's|^NAME=.*$|NAME=\"CachyOS Linux\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"CachyOS Linux\"|' \
        -e 's|^ID=.*$|ID=cachyos|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^ANSI_COLOR=.*$|ANSI_COLOR=38;2;23;147;209|' \        
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://cachyos.org/\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://wiki.cachyos.org/\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://forum.cachyos.org/\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/cachyos\"|' \
        -e 's|^LOGO=.*$|LOGO=cachyos|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi

    if [ -r $cachyosfile ] ; then
        # fix BUILD_ID for Cachy OS
        local buildid="$(grep "^VERSION=" $cachyosfile | awk '{print $1}' | cut -d '=' -f 2)"
        sed -i $file -e "s|^BUILD_ID=.*$|BUILD_ID=$buildid|"
    fi
}

Issues() {
    sed -i 's|Arch Linux|Cachy OS Linux|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"
